### ISSUE TITLE
不再更新了么

### ISSUE THREAD

**Issue by yyxida** [iAcn/BiliNeat#12]
5.8不适配了吗？都要出5.9了

**Comment by iAcn** [comment]
抱歉，我上 7.1 了，暂时停更

**Comment by yyxida** [comment]
好吧，有点可惜，这么好一个反逸插件。挺喜欢的，还是感谢这么久以来的更新！

**Comment by Z4HD** [comment]
@yyxida 接力，请

****

另：如对issue 的结果感到满意，请及时Close，3Q2X。

**Comment by yyxida** [comment]
@Z4HD 接不起接不起，我也就是个在GitHub上混脸熟的小白，啥都不懂
