### ISSUE TITLE
求解 7.1.2上2.0.6版本停止运行

### ISSUE THREAD

**Issue by JoannaLPY** [iAcn/BiliNeat#14]
RT

**Comment by Z4HD** [comment]
### Android 7 IS DUST
### 444 IS GOD

***

当然这年头兼容性最好、份额最大的已经变成5.1了，，，

**Comment by iAcn** [comment]
很抱歉这么久才回复你的 Issue... 由于 2.0.6 在测试的时候 Xposed for Nougat 并没有发布，所以这个问题我无法解答
