### ISSUE TITLE
我clone一下改下源码不介意吧

### ISSUE THREAD

**Issue by qtiuto** [iAcn/BiliNeat#5]
我看下能不能弄掉推荐里面的广告(应该可以)，破解下会员(不清楚，没看，有建议吗)

**Comment by iAcn** [comment]
可以。另外推荐内的广告我已经去除了呀，难道还有？会员的话 1080P 部分是根据请求带的 Token 来判断是否有 1080P 的，其他地方我没有仔细看。如果能解决的话可以给我发 PR 😂

**Comment by Z4HD** [comment]
你克隆之后在遵守GPL v3的前提下自己随便改随便用。只不过PR回去能不能并入master得iAcn神触表态。
---
建议你略微了解一下GPL v3，大有所益。
[GPLv3 zh-TW](http://www.chinasona.org/gnu/gnuv3-tc.html)

**Comment by Z4HD** [comment]
推荐的流程是先fork到自己的仓库，然后clone到本地，之后add+commit改爽了之后push。觉得有必要把更改送回自己原先fork的仓库可以发一个PullRequest（PR）。

如果直接clone的话你会发现你无法将修改推送至Github。

**Comment by iAcn** [comment]
楼上正确，GitHub 正常的协作就应该是这样的
