### ISSUE TITLE
Run.bat issue

### ISSUE THREAD

**Issue by WanderMax** [iAcn/BiliNeat#7]
Win 7 64 EN Python 3.61 x64
测试 BiliBili_4.33.0, 然后如图
![bilibili_4 33 0_log](https://cloud.githubusercontent.com/assets/15909056/25771810/9ffd9d8e-328e-11e7-93ed-a9f5e289a032.png)

**Comment by WanderMax** [comment]
测试5.40 运行闪退失败

**Comment by iAcn** [comment]
哔哩哔哩新版本有些变动，只是最近一直很忙，还没来得及更新自动适配脚本

**Comment by WanderMax** [comment]
上面那个乱码是怎么回事儿?

**Comment by iAcn** [comment]
乱码应该不是适配脚本的问题，因为脚本里并没有输出中文
