### ISSUE TITLE
从服务器获取配置文件的界面不够直观

### ISSUE THREAD

**Issue by Z4HD** [iAcn/BiliNeat#8]
建议恢复1.9.5版本的净化详情页面，最好在该页面中显示下列内容：
* 当前已安装的bilibili客户端版本
* 当前服务器中支持的Bilibili客户端版本
* 当前客户端中已载入的配置文件
* Xposed框架状态
* 净化状态

亦可在设置中添加手动加载配置文件的选项，方便暂时无法联网的用户。

同时不建议把```http://api.iacn.me/bilineat/```写死在代码中，最好在设置里添加设置配置文件服务器的选项。这样以后更换API服务器域名后不需修改代码，只需更改客户端设置即可。同时也方便其他人架设BiliNeat服务端。

**Comment by iAcn** [comment]
因为已经有了根据官方版本自动下载配置文件的功能，所以我感觉再显示 **当前已支持的 BiliBili 版本** 就没有很大的必要了。**当前客户端中已载入的配置文件** 这个受限于跨应用的权限问题，暂时无法实现。至于 **手动设置配置文件服务器** 一项，说实话，从 BiliNeat 开源到现在，我只收到过一个人给我贡献代码。。所以，估计自己架设净化服务器的就更少了2333。。。

**Comment by Z4HD** [comment]
感谢神触百忙之中抽出时间来回复我的issue，有幸收到您的回复本人深感荣幸。尽管我非常想在使用BiliNeta时能知晓当前支持净化的bilibili客户端版本以决定安装哪个版本的bilibili客户端，但相信神触经过周密客观全面的思考后得出的结论定是正确无疑的，我等

**Comment by Z4HD** [comment]
感谢神触百忙之中抽出时间来回复我的黑屁issue，有幸收到您的回复本人深感荣幸。尽管我非常希望在使用BiliNeta时能知晓当前支持净化的bilibili客户端版本以决定安装哪个版本的bilibili客户端，但相信神触您经过周密客观全面的思考后得出的结论定是正确无疑的，无需我等无能小鬼指点江山。本人不得不对神触您的包容与耐心感激涕零。

**Comment by Z4HD** [comment]
感谢神触百忙之中抽出时间来回复我的黑屁issue，有幸收到您的回复本人深感荣幸。尽管我非常希望在使用BiliNeta时能知晓当前支持净化的bilibili客户端版本以决定安装哪个版本的bilibili客户端，但相信神触您经过周密客观全面的思考后得出的结论定是正确无疑的，无需我等无能小鬼指点江山。本人不得不对神触您的包容与耐心感激涕零。
