### ISSUE TITLE
請問目前適配到哪個版本呢？

### ISSUE THREAD

**Issue by partment** [iAcn/BiliNeat#9]
如題

**Comment by iAcn** [comment]
哔哩哔哩 5.6.0 正式版

**Comment by at01076172** [comment]
但用5.6.0的apk拖進run.bat，仍然有出現NotFound。
能夠麻煩@iAcn 作者再幫忙確認一下嗎？
https://i.imgur.com/X127Txp.png

**Comment by iAcn** [comment]
因为近期官方的 APK 结构变动较大，所以我暂时没有更新自动适配脚本

**Comment by partment** [comment]
可以直接編譯專案，會得到apk檔
